<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Admin\Article;

class ArticleSeeder extends Seeder
{
    public function run()
    {
        $articles = [
            // ========== STYLOS (categorie_id = 1) ==========
            [
                'code_barre' => 'STY001',
                'designation' => 'Stylo Bic Bleu',
                'description' => 'Stylo à bille bleu, écriture fine 0.7mm',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 150,
                'seuil_alerte' => 20,
                'seuil_critique' => 10,
                'prix_unitaire' => 1.50,
                'emplacement' => 'A-12',
                'statut' => 'actif',
                'categorie_id' => 1,
            ],
            [
                'code_barre' => 'STY002',
                'designation' => 'Stylo Bic Rouge',
                'description' => 'Stylo à bille rouge, écriture fine 0.7mm',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 120,
                'seuil_alerte' => 20,
                'seuil_critique' => 10,
                'prix_unitaire' => 1.50,
                'emplacement' => 'A-12',
                'statut' => 'actif',
                'categorie_id' => 1,
            ],
            [
                'code_barre' => 'STY003',
                'designation' => 'Stylo Bic Noir',
                'description' => 'Stylo à bille noir, écriture fine 0.7mm',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 130,
                'seuil_alerte' => 20,
                'seuil_critique' => 10,
                'prix_unitaire' => 1.50,
                'emplacement' => 'A-12',
                'statut' => 'actif',
                'categorie_id' => 1,
            ],
            [
                'code_barre' => 'STY004',
                'designation' => 'Stylo Plume Bleu',
                'description' => 'Stylo plume avec cartouches d\'encre bleue',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 30,
                'seuil_alerte' => 10,
                'seuil_critique' => 5,
                'prix_unitaire' => 12.00,
                'emplacement' => 'A-13',
                'statut' => 'actif',
                'categorie_id' => 1,
            ],
            [
                'code_barre' => 'STY005',
                'designation' => 'Marqueur Permanent',
                'description' => 'Marqueur indélébile, pointe fine',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 80,
                'seuil_alerte' => 15,
                'seuil_critique' => 8,
                'prix_unitaire' => 3.00,
                'emplacement' => 'A-14',
                'statut' => 'actif',
                'categorie_id' => 1,
            ],
            
            // ========== CAHIERS (categorie_id = 2) ==========
            [
                'code_barre' => 'CAH001',
                'designation' => 'Cahier A4 96 pages',
                'description' => 'Cahier grand format 21x29.7cm, couverture rigide',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 80,
                'seuil_alerte' => 15,
                'seuil_critique' => 8,
                'prix_unitaire' => 8.00,
                'emplacement' => 'B-05',
                'statut' => 'actif',
                'categorie_id' => 2,
            ],
            [
                'code_barre' => 'CAH002',
                'designation' => 'Cahier A5 48 pages',
                'description' => 'Cahier petit format 14.8x21cm',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 200,
                'seuil_alerte' => 30,
                'seuil_critique' => 15,
                'prix_unitaire' => 4.00,
                'emplacement' => 'B-05',
                'statut' => 'actif',
                'categorie_id' => 2,
            ],
            [
                'code_barre' => 'CAH003',
                'designation' => 'Carnet de notes',
                'description' => 'Petit carnet à spirale, 80 pages',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 100,
                'seuil_alerte' => 20,
                'seuil_critique' => 10,
                'prix_unitaire' => 5.00,
                'emplacement' => 'B-06',
                'statut' => 'actif',
                'categorie_id' => 2,
            ],
            
            // ========== CLES USB (categorie_id = 14) ==========
            [
                'code_barre' => 'USB001',
                'designation' => 'Clé USB 32 Go',
                'description' => 'Clé USB haute vitesse, USB 3.0, métallique',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 25,
                'seuil_alerte' => 10,
                'seuil_critique' => 5,
                'prix_unitaire' => 25.00,
                'emplacement' => 'C-08',
                'statut' => 'actif',
                'categorie_id' => 14,
            ],
            [
                'code_barre' => 'USB002',
                'designation' => 'Clé USB 64 Go',
                'description' => 'Clé USB grande capacité, USB 3.0',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 15,
                'seuil_alerte' => 8,
                'seuil_critique' => 3,
                'prix_unitaire' => 40.00,
                'emplacement' => 'C-08',
                'statut' => 'actif',
                'categorie_id' => 14,
            ],
            [
                'code_barre' => 'USB003',
                'designation' => 'Clé USB 16 Go',
                'description' => 'Clé USB classique, USB 2.0',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 40,
                'seuil_alerte' => 15,
                'seuil_critique' => 8,
                'prix_unitaire' => 15.00,
                'emplacement' => 'C-08',
                'statut' => 'actif',
                'categorie_id' => 14,
            ],
            
            // ========== SOURIS (categorie_id = 12) ==========
            [
                'code_barre' => 'SOU001',
                'designation' => 'Souris Optique USB',
                'description' => 'Souris filaire, 3 boutons, 1200 DPI',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 45,
                'seuil_alerte' => 15,
                'seuil_critique' => 8,
                'prix_unitaire' => 15.00,
                'emplacement' => 'C-07',
                'statut' => 'actif',
                'categorie_id' => 12,
            ],
            [
                'code_barre' => 'SOU002',
                'designation' => 'Souris Sans Fil',
                'description' => 'Souris sans fil, 2.4 GHz, 1600 DPI',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 20,
                'seuil_alerte' => 8,
                'seuil_critique' => 4,
                'prix_unitaire' => 35.00,
                'emplacement' => 'C-07',
                'statut' => 'actif',
                'categorie_id' => 12,
            ],
            
            // ========== CLAVIERS (categorie_id = 13) ==========
            [
                'code_barre' => 'CLV001',
                'designation' => 'Clavier USB AZERTY',
                'description' => 'Clavier filaire standard, touches silencieuses',
                'unite_mesure' => 'pièce',
                'quantite_stock' => 18,
                'seuil_alerte' => 8,
                'seuil_critique' => 4,
                'prix_unitaire' => 45.00,
                'emplacement' => 'C-06',
                'statut' => 'actif',
                'categorie_id' => 13,
            ],
            
            // ========== ENVELOPPES (categorie_id = 7) ==========
            [
                'code_barre' => 'ENV001',
                'designation' => 'Enveloppes A4',
                'description' => 'Enveloppes blanches format A4, lot de 10',
                'unite_mesure' => 'lot',
                'quantite_stock' => 50,
                'seuil_alerte' => 10,
                'seuil_critique' => 5,
                'prix_unitaire' => 7.50,
                'emplacement' => 'B-02',
                'statut' => 'actif',
                'categorie_id' => 7,
            ],
            [
                'code_barre' => 'ENV002',
                'designation' => 'Enveloppes à bulles',
                'description' => 'Enveloppes protectrices pour colis',
                'unite_mesure' => 'lot',
                'quantite_stock' => 30,
                'seuil_alerte' => 8,
                'seuil_critique' => 4,
                'prix_unitaire' => 12.00,
                'emplacement' => 'B-02',
                'statut' => 'actif',
                'categorie_id' => 7,
            ],
            
            // ========== PAPIER (categorie_id = 9) ==========
            [
                'code_barre' => 'PAP001',
                'designation' => 'Papier A4 80g',
                'description' => 'Ramette de 500 feuilles, papier blanc 80g/m²',
                'unite_mesure' => 'ramette',
                'quantite_stock' => 35,
                'seuil_alerte' => 10,
                'seuil_critique' => 5,
                'prix_unitaire' => 12.00,
                'emplacement' => 'B-03',
                'statut' => 'actif',
                'categorie_id' => 9,
            ],
            
            // ========== CONGELATEUR (categorie_id = 19) ==========
            [
                'code_barre' => 'LEG001',
                'designation' => 'Légumes surgelés',
                'description' => 'Mélange de légumes surgelés 1kg',
                'unite_mesure' => 'kg',
                'quantite_stock' => 100,
                'seuil_alerte' => 20,
                'seuil_critique' => 10,
                'prix_unitaire' => 4.50,
                'emplacement' => 'D-03',
                'statut' => 'actif',
                'categorie_id' => 19,
            ],
        ];

        foreach ($articles as $article) {
            Article::create($article);
        }
    }
}